// 単語データ
// level 1: 5年生基礎 (身の回り、家族、色、数)
// level 2: 5-6年生標準 (学校生活、動詞、形容詞、月・曜日)
// level 3: 6年生発展 (職業、国、過去形、未来、疑問詞)

// Rarity: 1(Normal), 2(Rare), 3(Super Rare), 4(Legendary)

window.VOCABULARY = [
    // --- LEVEL 1: BEGINNER (Grade 5 Basic) ---
    // Numbers & Colors
    { id: 'l1_1', word: 'one', jp: '1 (いち)', icon: '1️⃣', level: 1, rarity: 1 },
    { id: 'l1_2', word: 'two', jp: '2 (に)', icon: '2️⃣', level: 1, rarity: 1 },
    { id: 'l1_3', word: 'three', jp: '3 (さん)', icon: '3️⃣', level: 1, rarity: 1 },
    { id: 'l1_10', word: 'ten', jp: '10 (じゅう)', icon: '🔟', level: 1, rarity: 1 },
    { id: 'l1_11', word: 'eleven', jp: '11 (じゅういち)', icon: '🔢', level: 1, rarity: 1 },
    { id: 'l1_12', word: 'twelve', jp: '12 (じゅうに)', icon: '🕛', level: 1, rarity: 1 },
    { id: 'l1_20', word: 'twenty', jp: '20 (にじゅう)', icon: '2️⃣0️⃣', level: 1, rarity: 1 },
    { id: 'l1_red', word: 'red', jp: '赤', icon: '🟥', level: 1, rarity: 1 },
    { id: 'l1_blue', word: 'blue', jp: '青', icon: '🟦', level: 1, rarity: 1 },
    { id: 'l1_yellow', word: 'yellow', jp: '黄色', icon: '🟨', level: 1, rarity: 1 },
    { id: 'l1_green', word: 'green', jp: '緑', icon: '🟩', level: 1, rarity: 1 },
    { id: 'l1_black', word: 'black', jp: '黒', icon: '⬛', level: 1, rarity: 1 },
    { id: 'l1_white', word: 'white', jp: '白', icon: '⬜', level: 1, rarity: 1 },

    // Family & People
    { id: 'l1_fam1', word: 'family', jp: '家族', icon: '👨‍👩‍👧', level: 1, rarity: 1 },
    { id: 'l1_fam2', word: 'father', jp: 'お父さん', icon: '👨', level: 1, rarity: 1 },
    { id: 'l1_fam3', word: 'mother', jp: 'お母さん', icon: '👩', level: 1, rarity: 1 },
    { id: 'l1_fam4', word: 'brother', jp: '兄/弟', icon: '👦', level: 1, rarity: 1 },
    { id: 'l1_fam5', word: 'sister', jp: '姉/妹', icon: '👧', level: 1, rarity: 1 },
    { id: 'l1_fam6', word: 'friend', jp: '友達', icon: '🤝', level: 1, rarity: 1 },
    { id: 'l1_fam7', word: 'teacher', jp: '先生', icon: '👩‍🏫', level: 1, rarity: 1 },
    { id: 'l1_fam8', word: 'me', jp: '私', icon: '😊', level: 1, rarity: 1 },

    // Food & Fruit
    { id: 'l1_fd1', word: 'apple', jp: 'リンゴ', icon: '🍎', level: 1, rarity: 1 },
    { id: 'l1_fd2', word: 'banana', jp: 'バナナ', icon: '🍌', level: 1, rarity: 1 },
    { id: 'l1_fd3', word: 'orange', jp: 'オレンジ', icon: '🍊', level: 1, rarity: 1 },
    { id: 'l1_fd4', word: 'grape', jp: 'ぶどう', icon: '🍇', level: 1, rarity: 1 },
    { id: 'l1_fd5', word: 'peach', jp: 'もも', icon: '🍑', level: 1, rarity: 1 },
    { id: 'l1_fd6', word: 'melon', jp: 'メロン', icon: '🍈', level: 1, rarity: 1 },
    { id: 'l1_fd7', word: 'egg', jp: 'たまご', icon: '🥚', level: 1, rarity: 1 },
    { id: 'l1_fd8', word: 'milk', jp: '牛乳', icon: '🥛', level: 1, rarity: 1 },
    { id: 'l1_fd9', word: 'rice', jp: 'ごはん', icon: '🍚', level: 1, rarity: 1 },
    { id: 'l1_fd10', word: 'bread', jp: 'パン', icon: '🍞', level: 1, rarity: 1 },
    { id: 'l1_fd11', word: 'water', jp: '水', icon: '💧', level: 1, rarity: 1 },
    { id: 'l1_fd12', word: 'cake', jp: 'ケーキ', icon: '🍰', level: 1, rarity: 1 },
    { id: 'l1_fd13', word: 'pizza', jp: 'ピザ', icon: '🍕', level: 1, rarity: 1 },
    { id: 'l1_fd14', word: 'curry', jp: 'カレー', icon: '🍛', level: 1, rarity: 1 },

    // Animals
    { id: 'l1_an1', word: 'dog', jp: '犬', icon: '🐶', level: 1, rarity: 1 },
    { id: 'l1_an2', word: 'cat', jp: '猫', icon: '🐱', level: 1, rarity: 1 },
    { id: 'l1_an3', word: 'bird', jp: '鳥', icon: '🐦', level: 1, rarity: 1 },
    { id: 'l1_an4', word: 'rabbit', jp: 'うさぎ', icon: '🐰', level: 1, rarity: 1 },
    { id: 'l1_an5', word: 'lion', jp: 'ライオン', icon: '🦁', level: 1, rarity: 1 },
    { id: 'l1_an6', word: 'bear', jp: 'くま', icon: '🐻', level: 1, rarity: 1 },
    { id: 'l1_an7', word: 'panda', jp: 'パンダ', icon: '🐼', level: 1, rarity: 1 },
    { id: 'l1_an8', word: 'fish', jp: '魚', icon: '🐟', level: 1, rarity: 1 },

    // Daily Objects
    { id: 'l1_obj1', word: 'pen', jp: 'ペン', icon: '🖊️', level: 1, rarity: 1 },
    { id: 'l1_obj2', word: 'book', jp: '本', icon: '📚', level: 1, rarity: 1 },
    { id: 'l1_obj3', word: 'notebook', jp: 'ノート', icon: '📓', level: 1, rarity: 1 },
    { id: 'l1_obj4', word: 'eraser', jp: '消しゴム', icon: '🧼', level: 1, rarity: 1 },
    { id: 'l1_obj5', word: 'desk', jp: '机', icon: '🪑', level: 1, rarity: 1 },
    { id: 'l1_obj6', word: 'chair', jp: '椅子', icon: '💺', level: 1, rarity: 1 },
    { id: 'l1_obj7', word: 'bag', jp: 'かばん', icon: '🎒', level: 1, rarity: 1 },
    { id: 'l1_obj8', word: 'cap', jp: 'ぼうし', icon: '🧢', level: 1, rarity: 1 },
    { id: 'l1_obj9', word: 'cup', jp: 'カップ', icon: '☕', level: 1, rarity: 1 },
    { id: 'l1_obj10', word: 'ball', jp: 'ボール', icon: '⚽', level: 1, rarity: 1 },
    { id: 'l1_obj11', word: 'box', jp: '箱', icon: '📦', level: 1, rarity: 1 },
    { id: 'l1_obj12', word: 'bed', jp: 'ベッド', icon: '🛏️', level: 1, rarity: 1 },

    // Greeting & Basic
    { id: 'l1_gr1', word: 'hello', jp: 'こんにちは', icon: '👋', level: 1, rarity: 1 },
    { id: 'l1_gr2', word: 'goodbye', jp: 'さようなら', icon: '👋', level: 1, rarity: 1 },
    { id: 'l1_gr3', word: 'thank you', jp: 'ありがとう', icon: '🙏', level: 1, rarity: 1 },
    { id: 'l1_gr4', word: 'good morning', jp: 'おはよう', icon: '🌅', level: 1, rarity: 1 },
    { id: 'l1_gr5', word: 'good night', jp: 'おやすみ', icon: '💤', level: 1, rarity: 1 },
    { id: 'l1_gr6', word: 'happy', jp: '幸せな', icon: '😄', level: 1, rarity: 1 },
    { id: 'l1_gr7', word: 'sad', jp: '悲しい', icon: '😢', level: 1, rarity: 1 },
    { id: 'l1_gr8', word: 'yes', jp: 'はい', icon: '🙆', level: 1, rarity: 1 },
    { id: 'l1_gr9', word: 'no', jp: 'いいえ', icon: '🙅', level: 1, rarity: 1 },

    // --- LEVEL 2: INTERMEDIATE (Grade 5-6 Standard) ---
    // School Subjects & Places
    { id: 'l2_sch1', word: 'school', jp: '学校', icon: '🏫', level: 2, rarity: 2 },
    { id: 'l2_sch2', word: 'class', jp: '授業/クラス', icon: '👩‍🏫', level: 2, rarity: 2 },
    { id: 'l2_sch3', word: 'English', jp: '英語', icon: '🔤', level: 2, rarity: 2 },
    { id: 'l2_sch4', word: 'Japanese', jp: '国語', icon: '📖', level: 2, rarity: 2 },
    { id: 'l2_sch5', word: 'math', jp: '算数', icon: '➗', level: 2, rarity: 2 },
    { id: 'l2_sch6', word: 'science', jp: '理科', icon: '🔬', level: 2, rarity: 2 },
    { id: 'l2_sch7', word: 'music', jp: '音楽', icon: '🎵', level: 2, rarity: 2 },
    { id: 'l2_sch8', word: 'art', jp: '図工', icon: '🎨', level: 2, rarity: 2 },
    { id: 'l2_sch9', word: 'PE', jp: '体育', icon: '🏃', level: 2, rarity: 2 },
    { id: 'l2_sch10', word: 'lunch', jp: '給食/昼食', icon: '🍱', level: 2, rarity: 2 },
    { id: 'l2_plc1', word: 'gym', jp: '体育館', icon: '🏀', level: 2, rarity: 2 },
    { id: 'l2_plc2', word: 'library', jp: '図書室', icon: '📚', level: 2, rarity: 2 },
    { id: 'l2_plc3', word: 'park', jp: '公園', icon: '⛲', level: 2, rarity: 2 },
    { id: 'l2_plc4', word: 'hospital', jp: '病院', icon: '🏥', level: 2, rarity: 2 },
    { id: 'l2_plc5', word: 'station', jp: '駅', icon: '🚉', level: 2, rarity: 2 },
    { id: 'l2_plc6', word: 'store', jp: '店', icon: '🏪', level: 2, rarity: 2 },
    { id: 'l2_plc7', word: 'pool', jp: 'プール', icon: '🏊', level: 2, rarity: 2 },
    { id: 'l2_plc8', word: 'kitchen', jp: '台所', icon: '🍳', level: 2, rarity: 2 },
    { id: 'l2_plc9', word: 'bathroom', jp: 'お風呂場', icon: '🛁', level: 2, rarity: 2 },

    // Action Verbs
    { id: 'l2_vb1', word: 'play', jp: '遊ぶ/する', icon: '🎮', level: 2, rarity: 2 },
    { id: 'l2_vb2', word: 'study', jp: '勉強する', icon: '✍️', level: 2, rarity: 2 },
    { id: 'l2_vb3', word: 'read', jp: '読む', icon: '📖', level: 2, rarity: 2 },
    { id: 'l2_vb4', word: 'write', jp: '書く', icon: '📝', level: 2, rarity: 2 },
    { id: 'l2_vb5', word: 'eat', jp: '食べる', icon: '🍽️', level: 2, rarity: 2 },
    { id: 'l2_vb6', word: 'drink', jp: '飲む', icon: '🥤', level: 2, rarity: 2 },
    { id: 'l2_vb7', word: 'run', jp: '走る', icon: '🏃', level: 2, rarity: 2 },
    { id: 'l2_vb8', word: 'walk', jp: '歩く', icon: '🚶', level: 2, rarity: 2 },
    { id: 'l2_vb9', word: 'swim', jp: '泳ぐ', icon: '🏊', level: 2, rarity: 2 },
    { id: 'l2_vb10', word: 'cook', jp: '料理する', icon: '🍳', level: 2, rarity: 2 },
    { id: 'l2_vb11', word: 'sing', jp: '歌う', icon: '🎤', level: 2, rarity: 2 },
    { id: 'l2_vb12', word: 'dance', jp: '踊る', icon: '💃', level: 2, rarity: 2 },
    { id: 'l2_vb13', word: 'watch', jp: '見る', icon: '📺', level: 2, rarity: 2 },
    { id: 'l2_vb14', word: 'listen', jp: '聞く', icon: '👂', level: 2, rarity: 2 },
    { id: 'l2_vb15', word: 'go', jp: '行く', icon: '➡️', level: 2, rarity: 2 },
    { id: 'l2_vb16', word: 'come', jp: '来る', icon: '⬅️', level: 2, rarity: 2 },
    { id: 'l2_vb17', word: 'like', jp: '好き', icon: '❤️', level: 2, rarity: 2 },
    { id: 'l2_vb18', word: 'want', jp: '欲しい', icon: '🤲', level: 2, rarity: 2 },
    { id: 'l2_vb19', word: 'have', jp: '持っている', icon: '🎒', level: 2, rarity: 2 },
    { id: 'l2_vb20', word: 'make', jp: '作る', icon: '🔨', level: 2, rarity: 2 },

    // Adjectives
    { id: 'l2_adj1', word: 'big', jp: '大きい', icon: '🐘', level: 2, rarity: 2 },
    { id: 'l2_adj2', word: 'small', jp: '小さい', icon: '🐜', level: 2, rarity: 2 },
    { id: 'l2_adj3', word: 'long', jp: '長い', icon: '📏', level: 2, rarity: 2 },
    { id: 'l2_adj4', word: 'short', jp: '短い', icon: '✏️', level: 2, rarity: 2 },
    { id: 'l2_adj5', word: 'hot', jp: '暑い/熱い', icon: '🥵', level: 2, rarity: 2 },
    { id: 'l2_adj6', word: 'cold', jp: '寒い/冷たい', icon: '🥶', level: 2, rarity: 2 },
    { id: 'l2_adj7', word: 'new', jp: '新しい', icon: '✨', level: 2, rarity: 2 },
    { id: 'l2_adj8', word: 'old', jp: '古い', icon: '📜', level: 2, rarity: 2 },
    { id: 'l2_adj9', word: 'nice', jp: 'すてきな', icon: '👍', level: 2, rarity: 2 },
    { id: 'l2_adj10', word: 'cute', jp: 'かわいい', icon: '🎀', level: 2, rarity: 2 },
    { id: 'l2_adj11', word: 'cool', jp: 'かっこいい', icon: '😎', level: 2, rarity: 2 },
    { id: 'l2_adj12', word: 'hungry', jp: 'お腹が空いた', icon: '🤤', level: 2, rarity: 2 },
    { id: 'l2_adj13', word: 'tired', jp: '疲れた', icon: '😫', level: 2, rarity: 2 },
    { id: 'l2_adj14', word: 'sleepy', jp: '眠い', icon: '😪', level: 2, rarity: 2 },

    // Days & Seasons
    { id: 'l2_tm1', word: 'Sunday', jp: '日曜日', icon: '☀️', level: 2, rarity: 2 },
    { id: 'l2_tm2', word: 'Monday', jp: '月曜日', icon: '🌙', level: 2, rarity: 2 },
    { id: 'l2_tm3', word: 'Tuesday', jp: '火曜日', icon: '🔥', level: 2, rarity: 2 },
    { id: 'l2_tm4', word: 'Wednesday', jp: '水曜日', icon: '💧', level: 2, rarity: 2 },
    { id: 'l2_tm5', word: 'Thursday', jp: '木曜日', icon: '🌲', level: 2, rarity: 2 },
    { id: 'l2_tm6', word: 'Friday', jp: '金曜日', icon: '💰', level: 2, rarity: 2 },
    { id: 'l2_tm7', word: 'Saturday', jp: '土曜日', icon: '🏔️', level: 2, rarity: 2 },
    { id: 'l2_tm8', word: 'spring', jp: '春', icon: '🌸', level: 2, rarity: 2 },
    { id: 'l2_tm9', word: 'summer', jp: '夏', icon: '🌻', level: 2, rarity: 2 },
    { id: 'l2_tm10', word: 'fall', jp: '秋', icon: '🍁', level: 2, rarity: 2 },
    { id: 'l2_tm11', word: 'winter', jp: '冬', icon: '⛄', level: 2, rarity: 2 },
    { id: 'l2_tm12', word: 'today', jp: '今日', icon: '📅', level: 2, rarity: 2 },
    { id: 'l2_tm13', word: 'tomorrow', jp: '明日', icon: '🔜', level: 2, rarity: 2 },
    { id: 'l2_tm14', word: 'yesterday', jp: '昨日', icon: '🔙', level: 2, rarity: 2 },
    { id: 'l2_tm15', word: 'birthday', jp: '誕生日', icon: '🎂', level: 2, rarity: 2 },

    // --- LEVEL 3: ADVANCED (Grade 6+ Challenge) ---
    // Jobs
    { id: 'l3_job1', word: 'doctor', jp: '医者', icon: '👨‍⚕️', level: 3, rarity: 3 },
    { id: 'l3_job2', word: 'teacher', jp: '先生', icon: '👩‍🏫', level: 3, rarity: 3 },
    { id: 'l3_job3', word: 'pilot', jp: 'パイロット', icon: '👨‍✈️', level: 3, rarity: 3 },
    { id: 'l3_job4', word: 'cook', jp: '料理人', icon: '👨‍🍳', level: 3, rarity: 3 },
    { id: 'l3_job5', word: 'singer', jp: '歌手', icon: '🎤', level: 3, rarity: 3 },
    { id: 'l3_job6', word: 'artist', jp: '芸術家', icon: '🎨', level: 3, rarity: 3 },
    { id: 'l3_job7', word: 'soccer player', jp: 'サッカー選手', icon: '⚽', level: 3, rarity: 3 },
    { id: 'l3_job8', word: 'police officer', jp: '警察官', icon: '👮', level: 3, rarity: 3 },
    { id: 'l3_job9', word: 'firefighter', jp: '消防士', icon: '🚒', level: 3, rarity: 3 },
    { id: 'l3_job10', word: 'vet', jp: '獣医', icon: '🐹', level: 3, rarity: 3 },
    { id: 'l3_job11', word: 'baker', jp: 'パン屋', icon: '🍞', level: 3, rarity: 3 },
    { id: 'l3_job12', word: 'dentist', jp: '歯医者', icon: '🦷', level: 3, rarity: 3 },
    { id: 'l3_job13', word: 'farmer', jp: '農家', icon: '🚜', level: 3, rarity: 3 },
    { id: 'l3_job14', word: 'programmer', jp: 'プログラマー', icon: '💻', level: 3, rarity: 3 },

    // Countries & World
    { id: 'l3_wld1', word: 'Japan', jp: '日本', icon: '🇯🇵', level: 3, rarity: 3 },
    { id: 'l3_wld2', word: 'America', jp: 'アメリカ', icon: '🇺🇸', level: 3, rarity: 3 },
    { id: 'l3_wld3', word: 'Canada', jp: 'カナダ', icon: '🇨🇦', level: 3, rarity: 3 },
    { id: 'l3_wld4', word: 'Australia', jp: 'オーストラリア', icon: '🇦🇺', level: 3, rarity: 3 },
    { id: 'l3_wld5', word: 'China', jp: '中国', icon: '🇨🇳', level: 3, rarity: 3 },
    { id: 'l3_wld6', word: 'Korea', jp: '韓国', icon: '🇰🇷', level: 3, rarity: 3 },
    { id: 'l3_wld7', word: 'Brazil', jp: 'ブラジル', icon: '🇧🇷', level: 3, rarity: 3 },
    { id: 'l3_wld8', word: 'India', jp: 'インド', icon: '🇮🇳', level: 3, rarity: 3 },
    { id: 'l3_wld9', word: 'UK', jp: 'イギリス', icon: '🇬🇧', level: 3, rarity: 3 },
    { id: 'l3_wld10', word: 'France', jp: 'フランス', icon: '🇫🇷', level: 3, rarity: 3 },
    { id: 'l3_wld11', word: 'world', jp: '世界', icon: '🗺️', level: 3, rarity: 3 },
    { id: 'l3_wld12', word: 'earth', jp: '地球', icon: '🌍', level: 3, rarity: 3 },
    { id: 'l3_wld13', word: 'sea', jp: '海', icon: '🌊', level: 3, rarity: 3 },
    { id: 'l3_wld14', word: 'mountain', jp: '山', icon: '⛰️', level: 3, rarity: 3 },
    { id: 'l3_wld15', word: 'river', jp: '川', icon: '🏞️', level: 3, rarity: 3 },

    // Advanced Verbs & Concepts
    { id: 'l3_av1', word: 'enjoy', jp: '楽しむ', icon: '🥳', level: 3, rarity: 3 },
    { id: 'l3_av2', word: 'finish', jp: '終える', icon: '🏁', level: 3, rarity: 3 },
    { id: 'l3_av3', word: 'start', jp: '始める', icon: '🏁', level: 3, rarity: 3 },
    { id: 'l3_av4', word: 'stop', jp: '止まる', icon: '🛑', level: 3, rarity: 3 },
    { id: 'l3_av5', word: 'try', jp: 'やってみる', icon: '💪', level: 3, rarity: 3 },
    { id: 'l3_av6', word: 'learn', jp: '学ぶ', icon: '🧠', level: 3, rarity: 3 },
    { id: 'l3_av7', word: 'teach', jp: '教える', icon: '👩‍🏫', level: 3, rarity: 3 },
    { id: 'l3_av8', word: 'buy', jp: '買う', icon: '🛒', level: 3, rarity: 3 },
    { id: 'l3_av9', word: 'visit', jp: '訪れる', icon: '🏙️', level: 3, rarity: 3 },
    { id: 'l3_av10', word: 'travel', jp: '旅行する', icon: '✈️', level: 3, rarity: 3 },
    { id: 'l3_av11', word: 'speak', jp: '話す', icon: '🗣️', level: 3, rarity: 3 },
    { id: 'l3_av12', word: 'think', jp: '考える', icon: '🤔', level: 3, rarity: 3 },
    { id: 'l3_av13', word: 'know', jp: '知っている', icon: '💡', level: 3, rarity: 3 },
    { id: 'l3_av14', word: 'understand', jp: '理解する', icon: '👌', level: 3, rarity: 3 },
    { id: 'l3_av15', word: 'help', jp: '助ける', icon: '🆘', level: 3, rarity: 3 },
    { id: 'l3_av16', word: 'dream', jp: '夢', icon: '💭', level: 3, rarity: 3 },
    { id: 'l3_av17', word: 'future', jp: '未来', icon: '🚀', level: 3, rarity: 3 },
    { id: 'l3_av18', word: 'memory', jp: '思い出', icon: '📸', level: 3, rarity: 3 },
    { id: 'l3_av19', word: 'vacation', jp: '休暇', icon: '🏖️', level: 3, rarity: 3 },
    { id: 'l3_av20', word: 'festival', jp: '祭り', icon: '🏮', level: 3, rarity: 3 },
    { id: 'l3_av21', word: 'restaurant', jp: 'レストラン', icon: '🍽️', level: 3, rarity: 3 },
    { id: 'l3_av22', word: 'department store', jp: 'デパート', icon: '🏢', level: 3, rarity: 3 },

    // Adjectives 2
    { id: 'l3_adj1', word: 'beautiful', jp: '美しい', icon: '✨', level: 3, rarity: 3 },
    { id: 'l3_adj2', word: 'interesting', jp: '面白い', icon: '🤣', level: 3, rarity: 3 },
    { id: 'l3_adj3', word: 'difficult', jp: '難しい', icon: '🧩', level: 3, rarity: 3 },
    { id: 'l3_adj4', word: 'easy', jp: '簡単な', icon: '👌', level: 3, rarity: 3 },
    { id: 'l3_adj5', word: 'famous', jp: '有名な', icon: '🌟', level: 3, rarity: 3 },
    { id: 'l3_adj6', word: 'exciting', jp: 'わくわくする', icon: '😆', level: 3, rarity: 3 },
    { id: 'l3_adj7', word: 'strong', jp: '強い', icon: '💪', level: 3, rarity: 3 },
    { id: 'l3_adj8', word: 'kind', jp: '親切な', icon: '💗', level: 3, rarity: 3 },
    { id: 'l3_adj9', word: 'busy', jp: '忙しい', icon: '🏃‍♂️', level: 3, rarity: 3 },
    { id: 'l3_adj10', word: 'favorite', jp: 'お気に入りの', icon: '⭐', level: 3, rarity: 3 },
    { id: 'l3_adj11', word: 'delicious', jp: 'おいしい', icon: '😋', level: 3, rarity: 3 },
    { id: 'l3_adj12', word: 'great', jp: 'すばらしい', icon: '👏', level: 3, rarity: 3 },

    // Wh- Questions & Others
    { id: 'l3_wh1', word: 'what', jp: '何', icon: '❓', level: 3, rarity: 3 },
    { id: 'l3_wh2', word: 'who', jp: '誰', icon: '👤', level: 3, rarity: 3 },
    { id: 'l3_wh3', word: 'when', jp: 'いつ', icon: '⏰', level: 3, rarity: 3 },
    { id: 'l3_wh4', word: 'where', jp: 'どこ', icon: '🗺️', level: 3, rarity: 3 },
    { id: 'l3_wh5', word: 'why', jp: 'なぜ', icon: '🤔', level: 3, rarity: 3 },
    { id: 'l3_wh6', word: 'how', jp: 'どうやって', icon: '🛠️', level: 3, rarity: 3 },

    // --- ULTRA RARE (★4) LEGENDARY ---
    { id: 'ur_dragon', word: 'dragon', jp: 'ドラゴン', icon: '🐉', level: 3, rarity: 4 },
    { id: 'ur_universe', word: 'universe', jp: '宇宙', icon: '🌌', level: 3, rarity: 4 },
    { id: 'ur_hero', word: 'hero', jp: '英雄', icon: '🦸', level: 3, rarity: 4 },
    { id: 'ur_legend', word: 'legend', jp: '伝説', icon: '📜', level: 3, rarity: 4 },
    { id: 'ur_victory', word: 'victory', jp: '勝利', icon: '✌️', level: 3, rarity: 4 },
    { id: 'ur_treasure', word: 'treasure', jp: '宝物', icon: '💎', level: 3, rarity: 4 },
    { id: 'ur_adventure', word: 'adventure', jp: '冒険', icon: '🗺️', level: 3, rarity: 4 },
    { id: 'ur_rainbow', word: 'rainbow', jp: '虹', icon: '🌈', level: 3, rarity: 4 },
    { id: 'ur_peace', word: 'peace', jp: '平和', icon: '🕊️', level: 3, rarity: 4 },
    { id: 'ur_nature', word: 'nature', jp: '自然', icon: '🌿', level: 3, rarity: 4 },
    { id: 'ur_freedom', word: 'freedom', jp: '自由', icon: '🦅', level: 3, rarity: 4 },
    { id: 'ur_champion', word: 'champion', jp: 'チャンピオン', icon: '🏆', level: 3, rarity: 4 }
];

window.PHRASES = [
    // 挨拶・自己紹介
    { id: 'p_hello', word: 'Hello.', jp: 'こんにちは。', icon: '👋', level: 4 },
    { id: 'p_goodmorning', word: 'Good morning.', jp: 'おはようございます。', icon: '🌅', level: 4 },
    { id: 'p_nicetomeet', word: 'Nice to meet you.', jp: 'はじめまして。', icon: '🤝', level: 4 },
    { id: 'p_seeyou', word: 'See you.', jp: 'またね。', icon: '👋', level: 4 },
    { id: 'p_myname', word: 'My name is Ken.', jp: '私の名前はケンです。', icon: '📛', level: 4 },
    { id: 'p_from', word: 'I am from Japan.', jp: '私は日本出身です。', icon: '🇯🇵', level: 4 },
    { id: 'p_like', word: 'I like soccer.', jp: '私はサッカーが好きです。', icon: '⚽', level: 4 },
    { id: 'p_age', word: 'I am 12 years old.', jp: '私は12歳です。', icon: '🎂', level: 4 },

    // 質問・応答
    { id: 'p_howareyou', word: 'How are you?', jp: '元気ですか？', icon: '😊', level: 4 },
    { id: 'p_fine', word: 'I am fine.', jp: '元気です。', icon: '👍', level: 4 },
    { id: 'p_time', word: 'What time is it?', jp: '何時ですか？', icon: '🕒', level: 4 },
    { id: 'p_can', word: 'Can you play the piano?', jp: 'ピアノを弾けますか？', icon: '🎹', level: 4 },
    { id: 'p_doyoulike', word: 'Do you like baseball?', jp: '野球は好きですか？', icon: '⚾', level: 4 },
    { id: 'p_station', word: 'Where is the station?', jp: '駅はどこですか？', icon: '🚉', level: 4 },
    { id: 'p_dream', word: 'What do you want to be?', jp: '何になりたいですか？', icon: '💭', level: 4 },
    { id: 'p_weather', word: 'How is the weather?', jp: '天気はどうですか？', icon: '☀', level: 4 },

    // 日常会話
    { id: 'p_thankyou', word: 'Thank you.', jp: 'ありがとう。', icon: '🎁', level: 4 },
    { id: 'p_welcome', word: "You're welcome.", jp: 'どういたしまして。', icon: '💁', level: 4 },
    { id: 'p_sorry', word: "I'm sorry.", jp: 'ごめんなさい。', icon: '🙇', level: 4 },
    { id: 'p_excuse', word: 'Excuse me.', jp: 'すみません。', icon: '🗣️', level: 4 },
    { id: 'p_lets', word: "Let's go.", jp: '行きましょう。', icon: '🏃', level: 4 },
    { id: 'p_right', word: "That's right.", jp: 'その通りです。', icon: '⭕', level: 4 },
    { id: 'p_metoo', word: 'Me too.', jp: '私もです。', icon: '✋', level: 4 },
    { id: 'p_hungry', word: "I'm hungry.", jp: 'お腹が空きました。', icon: '🍴', level: 4 },
    { id: 'p_delicious', word: "It's delicious.", jp: 'おいしいです。', icon: '😋', level: 4 }
];